#Data Cleaning

Using this colab to just code out the data cleaning part. Filtering tweets to only include New York tweets and tweets related to mental health based on certain words:
-

In [1]:
import pandas as pd

In [2]:
#Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
all = pd.read_csv("/content/drive/MyDrive/Data Science/ATDS Final Project/total_tweets.csv")
all

FileNotFoundError: ignored

In [ ]:
# Extract only New York City (New York, NY) tweets --> New York, Manhattan, Brooklyn, Queens, Bronx, Staten Island
nyc = all.loc[all['city'].isin(['New York, NY', 'Manhattan, NY', 'Brooklyn, NY', 'Queens, NY', 'Bronx, NY', 'Staten Island, NY'])]
nyc

#For New York STATE --> if using this, CHANGE nyc dataframe to ny below

all = all.dropna()
ny = all[all['city'].str.contains(' NY')]
ny

,date,text,sentiment,retweet_count,country,city
37,2020-3-21,"['Even', 'Dr', 'Fauci', 'cant', 'take', 'his',...",-0.204545,0,United States,"Manhattan, NY"
39,2020-3-21,"['covid19', 'duxduce', 'corona', 'beer', 'vs',...",0.136364,0,United States,"Queens, NY"
219,2020-3-21,"['We', 'are', 'continuing', 'to', 'monitor', '...",0.327273,0,United States,"Manhattan, NY"
238,2020-3-21,"['Corona', 'NY', 'Sat', 'Mar', '21st', 'AM', '...",0.425000,0,United States,"Queens, NY"
262,2020-3-21,"['Oreo', '“you’re', 'gonna', 'be', 'here', 'al...",0.000000,0,United States,"Queens, NY"
...,...,...,...,...,...,...
350376,2021-7-20,"['Just', 'posted', 'a', 'video', 'Flushing', '...",0.000000,0,United States,"Queens, NY"
350472,2021-7-20,"['Safe', 'entertaining', 'tips', 'for', 'grand...",0.000000,0,United States,"Manhattan, NY"
350521,2021-7-20,"['Summer', 'haircut', 'Wearing', 'a', 'mask', ...",0.100000,0,United States,"Brooklyn, NY"
350575,2021-7-20,"['The', 'fact', 'that', 'I', 'was', 'able', 't...",0.070833,0,United States,"Manhattan, NY"
350578,2021-7-20,"['COVID', 'has', 'us', 'leaning', 'on', 'each'...",0.100000,0,United States,"Brooklyn, NY"

In [ ]:
# Extract only mental health related tweets (iterate through every row 'text' and if word = 'mental' in list, add that row to df, and move to next column)

#Intialize empty dataframe
df = pd.DataFrame(columns = ['date', 'text', 'sentiment', 'retweet_count', 'country', 'city'])

#Iterate through text column in nyc dataframe, collect indices of entries that include keywords
mh_indices = []
mental_health_words = ['mental', 'anxiety', 'depression', 'worried', 'anxious', 'scared', 'depressed']
for column, row in nyc['text'].iteritems(): #column = index, row = text
  for j in mental_health_words:
    if j in row:
      mh_indices.append(column)

#Add mental health related entries to new dataframe 
for i in mh_indices:
  entry = nyc.loc[i]
  df = df.append([entry])

df

,date,text,sentiment,retweet_count,country,city
1635,2020-3-22,"['The', 'rona', 'won’t', 'stop', 'my', 'creati...",-0.500000,0,United States,"Manhattan, NY"
9473,2020-4-3,"['I', 'guess', 'when', 'I', 'wrote', 'this', '...",0.200000,0,United States,"Manhattan, NY"
9726,2020-4-3,"['Dear', 'Corona', 'You', 'keep', 'us', 'indoo...",-0.200000,0,United States,"Manhattan, NY"
11093,2020-4-5,"['Blog', 'the', 'all', 'is', 'mind', 'the', 'u...",0.000000,0,United States,"Brooklyn, NY"
11282,2020-4-6,"['Dominos', 'Pizza', 'New', 'York', 'New', 'Yo...",0.000000,0,United States,"Manhattan, NY"
...,...,...,...,...,...,...
281767,2021-2-4,"['Dickson', 'Bowman', 'interviews', 'Kelly', '...",0.525000,0,United States,"Manhattan, NY"
282438,2021-2-5,"['Sharing', 'the', 'wired', 'story', 'on', 'ou...",-0.266667,0,United States,"Manhattan, NY"
288204,2021-2-17,"['LGA', 'airport', 'Why', 'did', 'no', 'one', ...",0.483333,1,United States,"Queens, NY"
295245,2021-3-6,"['So', 'how', 'many', 'of', 'y’all', 'got', 't...",-0.200000,1,United States,"Brooklyn, NY"
307652,2021-3-31,"['Havent', 'been', 'on', 'a', 'train', 'like',...",0.000000,0,United States,"Queens, NY"